### ISSUE TITLE
模型缺乏泛化性

### ISSUE THREAD

**Issue by stellarfeline** [JiageWang/hand-writing-recognition#3]
今天训练了一下，20个epoch跑下来测试集识别正确率能到91%，但是我用同样的的方法（输入图片保留3通道，尺寸缩放到64*64）把一些自己写的单个字图片输入到模型中预测出来结果准确率非常低，下一步尝试更改一下模型结构来提高泛化性。

**Comment by caigouShaw** [comment]
请问有测试代码吗？
